<template>
  <div class="container mt-5">
    <b-row>
      <b-col>
        <b-table
          stacked="md"
          show-empty
          :items="teamCompositionsFromDatabase"
          :fields="teamCompositionsTableFields"
          class="text-white"
        >
          <template slot="tier" slot-scope="row">
            <div class="table__tier-number mx-auto">
              {{ convertTierNumberToLetter(row.item.tier) }}
            </div>
          </template>
          <template slot="synergies" slot-scope="row">
            <div
              v-for="synergy in getSynergiesSorted(row.item.synergies)"
              :key="synergy.type"
              class="d-inline-block ml-3"
            >
              <img
                :src="getClassOrOriginThumbnailImage(synergy.type)"
                alt=""
                class="class-or-origin-thumbnail__image d-block mx-auto"
              />
              <span class="font-weight-bold">
                {{ synergy.type }}
              </span>
            </div>
          </template>
          <template slot="size" slot-scope="row">
            <span class="font-weight-bold">{{
              row.item.championNames.length
            }}</span>
          </template>

          <template slot="champions" slot-scope="row">
            <mq-layout mq="lg+">
              <div
                v-for="champion in getChampionsSortedByCost(row.item.champions)"
                :key="champion.key"
                class="d-inline-block"
              >
                <div
                  class="champion-thumbnail champion-thumbnail__image-container d-inline-block"
                  :class="getChampionThumbnailContainerClass(champion)"
                >
                  <img
                    :src="getChampionThumbnailImage(champion.key)"
                    alt="Image of a champion that is a part of a team composition generated by the user's input"
                    class="champion-thumbnail champion-thumbnail__image"
                  />
                </div>
                <span class="d-block">{{ champion.name }}</span>
              </div>
            </mq-layout>

            <mq-layout :mq="['sm', 'md']">
              <div
                v-for="champion in getChampionsSortedByCost(row.item.champions)"
                :key="champion.key"
                class="d-flex justify-content-center"
              >
                <div class="d-flex flex-column align-items-start mb-2">
                  <div>{{ champion.name }}</div>
                  <div class="item-hl d-flex align-items-center border-bottom">
                    <div
                      class="champion-thumbnail champion-thumbnail__image-container d-inline-block"
                      :class="getChampionThumbnailContainerClass(champion)"
                    >
                      <img
                        :src="getChampionThumbnailImage(champion.key)"
                        alt="Image of a champion that is a part of a team composition generated by the user's input"
                        class="champion-thumbnail champion-thumbnail__image"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </mq-layout>
          </template>

          <template slot="deleteComp" slot-scope="row">
            <button
              class="btn btn-warning"
              @click="deleteTeamCompositionFromDatabase(row.item.id)"
            >
              Delete
            </button>
          </template>
        </b-table>
      </b-col>
    </b-row>
  </div>
</template>

<script>
import db from "../firebaseConfig";
import championTables from "../mixins/team_composition_tables";

export default {
  data() {
    return {
      teamCompositionsFromDatabase: [],
      teamCompositionsTableFields: [
        { key: "tier", sortable: true },
        { key: "championNames.length", label: "Team Size", sortable: true },
        { key: "synergies" },
        { key: "champions" },
        { key: "deleteComp" }
      ]
    };
  },

  mixins: [championTables],

  methods: {
    capitalizeFirstLetter: string => {
      return string.charAt(0).toUpperCase() + string.slice(1);
    },
    deleteTeamCompositionFromDatabase(docId) {
      db.collection("compositions")
        .doc(docId)
        .delete()
        .then(() => console.log("success"))
        .catch(err => console.log(err));
    },
    compareChampionCost: function(a, b) {
      if (a.cost < b.cost) {
        return -1;
      }
      if (a.cost > b.cost) {
        return 1;
      }
      return 0;
    }
  },
  created() {
    db.collection("compositions")
      .get()
      .then(teamCompositionsQuerySnapshot => {
        teamCompositionsQuerySnapshot.forEach(itemDoc => {
          this.teamCompositionsFromDatabase.push(itemDoc.data());
        });
      });
  }
};
</script>

<style lang="scss" scoped>
.table_popover-body {
  background: #947b4a;
}
.table__tier-number {
  font-size: 30px;
  font-weight: bold;
  height: 50px;
  width: 52px;
  border: 3px solid #c4ac76;
  border-radius: 50%;
}
.class-or-origin-thumbnail__image {
  height: 45px;
}
.champion-thumbnail {
  -webkit-clip-path: polygon(
    50% 6%,
    89% 24%,
    89% 76%,
    50% 94%,
    11% 74%,
    11% 26%
  );
  clip-path: polygon(50% 6%, 89% 24%, 89% 76%, 50% 94%, 11% 74%, 11% 26%);
}
.champion-thumbnail__image-container {
  display: inline-block;
  position: relative;
  width: 60px;
  height: 60px;
}
.champion-thumbnail__image-container--5-cost {
  background: #f9ce69;
}
.champion-thumbnail__image-container--4-cost {
  background: #601e79;
}
.champion-thumbnail__image-container--3-cost {
  background: #4a9fe0;
}
.champion-thumbnail__image-container--2-cost {
  background: #1e9539;
}
.champion-thumbnail__image-container--1-cost {
  background: #ffffff;
}
.champion-thumbnail__image {
  position: absolute;
  top: 3px;
  left: 3px;
  width: 54px;
  height: 54px;
}
.item-thumbnail__image {
  height: 40px;
  transition: 0.25s;
  transition-timing-function: ease-in-out;
  &:hover {
    transform: scale(1.05);
  }
}
td::before {
  text-align: center !important;
  width: 100% !important;
}
td > div {
  padding: 0rem !important;
}

@media screen and (max-width: 768px) {
  .table__tier-number {
    font-size: 30px;
    font-weight: bold;
    height: 50px;
    width: 52px;
  }
  .class-or-origin-thumbnail__image {
    height: 35px;
  }
  .champion-thumbnail__image-container {
    display: inline-block;
    position: relative;
    width: 50px;
    height: 50px;
  }
  .champion-thumbnail__image {
    position: absolute;
    top: 3px;
    left: 3px;
    width: 44px;
    height: 44px;
  }
  .item-thumbnail__image {
    height: 36px;
  }
  td::before {
    color: #ffffff;
    font-size: 19px;
    margin-bottom: 20px !important;
  }
  td {
    border-bottom: 1px;
    font-weight: bold;
    color: #d3d3d3 !important;
  }
  tr > td:first-of-type > div {
    font-size: 25px !important;
  }
}
</style>
