<template>
  <b-row>
    <b-col md="10" offset="1">
      <b-table
        stacked="md"
        show-empty
        empty-text="No team comps found using given champion(s)"
        :items="teamCompositionsToRender"
        :fields="teamCompositionsToRenderFields"
        class="text-white"
      >
        <template slot="synergies" slot-scope="row">
          <div
            v-for="synergy in row.item.synergies"
            class="d-inline-block mx-2"
          >
            <img
              :src="getClassOrOriginThumbnailImage(synergy.type)"
              alt=""
              class="d-block"
            />
            <span class="font-weight-bold">
              {{ synergy.type }}
            </span>
          </div>
        </template>
        <template slot="size" slot-scope="row">
          <span class="font-weight-bold">{{
            row.item.championNames.length
          }}</span>
        </template>
        <template slot="champions" slot-scope="row">
          <div
            v-for="champion in sortChampionsByCost(row.item.champions)"
            class="champion-thumbnail champion-thumbnail-image-container d-inline-block"
            :class="getChampionThumbnailContainerClass(champion)"
          >
            <img
              :src="getChampionThumbnailImage(champion.key)"
              alt="Image of a champion that is a part of a team composition generated by the user's input"
              class="champion-thumbnail champion-thumbnail-image"
            />
          </div>
        </template>
      </b-table>
    </b-col>
  </b-row>
</template>

<script>
import db from "../firebaseConfig";

export default {
  data() {
    return {
      availableChampions: [],
      teamCompositionsToRenderFields: [
        { key: "size", sortable: true },
        { key: "synergies" },
        { key: "champions" }
      ]
    };
  },
  props: ["teamCompositionsToRender"],
  methods: {
    getChampionThumbnailImage(championName) {
      return require(`@/assets/images/championImages/${this.capitalizeFirstLetter(
        championName
      )}.png`);
    },
    getClassOrOriginThumbnailImage(classOrOriginName) {
      return require(`@/assets/images/classAndOriginImages/${this.capitalizeFirstLetter(
        classOrOriginName
      )}.png`);
    },
    getChampionThumbnailContainerClass(champion) {
      return {
        'champion-thumbnail-image-container-5-cost': champion.cost === 5,
        'champion-thumbnail-image-container-4-cost': champion.cost === 4,
        'champion-thumbnail-image-container-3-cost': champion.cost === 3,
        'champion-thumbnail-image-container-2-cost': champion.cost === 2,
        'champion-thumbnail-image-container-1-cost': champion.cost === 1
      }
    },
    capitalizeFirstLetter: string => {
      return string.charAt(0).toUpperCase() + string.slice(1);
    },
    sortChampionsByCost: function(champions) {
      const championsSortedByCost = champions.sort(this.compare);
      return championsSortedByCost;
    },
    compare: function(a, b) {
      if (a.cost < b.cost) {
        return -1;
      }
      if (a.cost > b.cost) {
        return 1;
      }
      return 0;
    }
  },
  created() {
    db.collection("champions")
      .get()
      .then(championsQuerySnapshot => {
        championsQuerySnapshot.forEach(championDoc => {
          const champion = championDoc.data();
          champion.name = championDoc.id;
          this.availableChampions.push(champion);
        });
      });
  }
};
</script>

<style>
.champion-thumbnail {
  -webkit-clip-path: polygon(
    50% 6%,
    89% 24%,
    89% 76%,
    50% 94%,
    11% 74%,
    11% 26%
  );
  clip-path: polygon(50% 6%, 89% 24%, 89% 76%, 50% 94%, 11% 74%, 11% 26%);
}
.champion-thumbnail-image-container {
  display: inline-block;
  position: relative;
  width: 60px;
  height: 60px;
}
.champion-thumbnail-image-container-5-cost {
    background: #F9CE69;
}
.champion-thumbnail-image-container-4-cost {
    background: #601E79;
}
.champion-thumbnail-image-container-3-cost {
    background: #4A9FE0;
}
.champion-thumbnail-image-container-2-cost {
    background: #1e9539;
}
.champion-thumbnail-image-container-1-cost {
    background: #ffffff;
}
.champion-thumbnail-image {
    position: absolute;
    top: 3px;
    left: 3px;
    width: 54px;
    height: 54px;
}
</style>
