<template>
  <b-row>
    <b-col>
      <b-table
        v-if="selectedChampions.length !== 0"
        stacked="md"
        show-empty
        :empty-text="getTableEmptyText()"
        :items="teamCompositionsToRender"
        :fields="teamCompositionsToRenderFields"
        class="text-white"
        sort-by="tier"
      >
        <template slot="tier" slot-scope="row">
          <div class="tier-number mx-auto">
            {{ convertTierNumberToLetter(row.item.tier) }}
          </div>
        </template>
        <template slot="synergies" slot-scope="row">
          <div
            v-for="synergy in getSynergiesSorted(row.item.synergies)"
            :key="synergy.type"
            class="d-inline-block ml-3"
          >
            <img
              :src="getClassOrOriginThumbnailImage(synergy.type)"
              alt=""
              class="class-or-origin-thumbnail-image d-block mx-auto"
            />
            <span class="font-weight-bold">
              {{ synergy.type }}
            </span>
          </div>
        </template>
        <template slot="size" slot-scope="row">
          <span class="font-weight-bold">{{
            row.item.championNames.length
          }}</span>
        </template>

        <template slot="champions" slot-scope="row">
          <mq-layout mq="lg+">
            <div
              v-for="(champion, index) in getChampionsSortedByCost(
                row.item.champions
              )"
              :key = index
              class="d-inline-block"
            >
              <div
                class="champion-thumbnail champion-thumbnail-image-container d-inline-block"
                :class="getChampionThumbnailContainerClass(champion)"
              >
                <img
                  :src="getChampionThumbnailImage(champion.key)"
                  alt="Image of a champion that is a part of a team composition generated by the user's input"
                  class="champion-thumbnail champion-thumbnail-image"
                />
              </div>
              <span class="d-block">{{ champion.name }}</span>
              <div>
                <div v-for="item in champion.items">
                  <img
                    :src="getItemThumbnailImage(item)"
                    alt=""
                    class="item-thumbnail-image my-1 d-block mx-auto"
                    :id="row.index + item + champion.key"
                  />
                  <b-popover
                    title=""
                    :target="row.index + item + champion.key"
                    placement="lefttop"
                    triggers="hover click"
                    variant="primary"
                  >
                    <img
                      :src="
                      getItemComponentThumbnailImage(item, 0)"
                      alt=""
                      class="mr-3 "
                    />
                    <img
                      :src="getItemComponentThumbnailImage(item, 1)"
                      alt=""
                    />
                  </b-popover>
                </div>
              </div>
            </div>
          </mq-layout>

          <mq-layout :mq="['sm', 'md']">
            <div
              v-for="(champion, index) in getChampionsSortedByCost(
                row.item.champions
              )"
              :key = index
              class="d-flex justify-content-center"
            >
              <div class="d-flex flex-column align-items-start mb-2">
                <div>{{ champion.name }}</div>
                <div class="item-hl d-flex align-items-center border-bottom">
                  <div
                    class="champion-thumbnail champion-thumbnail-image-container d-inline-block"
                    :class="getChampionThumbnailContainerClass(champion)"
                  >
                    <img
                      :src="getChampionThumbnailImage(champion.key)"
                      alt="Image of a champion that is a part of a team composition generated by the user's input"
                      class="champion-thumbnail champion-thumbnail-image"
                    />
                  </div>

                  <div v-for="item in champion.items">
                    <b-popover
                      title=""
                      :target="row.index + item + champion.key + 'lol'"
                      :ref="row.index + item + champion.key"
                      placement="lefttop"
                      triggers="hover click"
                      variant="primary"
                    >
                      <template slot="title"></template>
                      <template
                        slot="content"
                        @click="
                          onMobileItemThumbnailImageClick(
                            row.index + item + champion.key
                          )
                        "
                        >Content via Slots</template
                      >
                    </b-popover>
                    <img
                      :src="getItemThumbnailImage(item)"
                      alt=""
                      class="item-thumbnail-image pl-2"
                      :id="row.index + item + champion.key + 'lol'"
                    />
                  </div>
                </div>
              </div>
            </div>
          </mq-layout>
        </template>
      </b-table>
    </b-col>
  </b-row>
</template>

<script>
import db from "../firebaseConfig";

export default {
  data() {
    return {
      availableChampions: [],
      teamCompositionsToRenderFields: [
        { key: "tier", sortable: true },
        { key: "championNames.length", label: "Team Size", sortable: true },
        { key: "synergies" },
        { key: "champions" }
      ],
      itemsFromDatabase: [],
      randomId: 0,
      selectedItem: ""
    };
  },
  props: ["teamCompositionsToRender", "selectedChampions"],

  methods: {
    getChampionThumbnailContainerClass(champion) {
      return {
        "champion-thumbnail-image-container-5-cost": champion.cost === 5,
        "champion-thumbnail-image-container-4-cost": champion.cost === 4,
        "champion-thumbnail-image-container-3-cost": champion.cost === 3,
        "champion-thumbnail-image-container-2-cost": champion.cost === 2,
        "champion-thumbnail-image-container-1-cost": champion.cost === 1
      };
    },
    getChampionThumbnailImage(championKey) {
      const formattedChampionName = this.formatChampionName(championKey);
      console.log(formattedChampionName)
      return require(`@/assets/images/championImages/${this.capitalizeFirstLetter(
        formattedChampionName
      )}.png`);
    },
    getClassOrOriginThumbnailImage(classOrOriginName) {
      return require(`@/assets/images/classAndOriginImages/${this.capitalizeFirstLetter(
        classOrOriginName
      )}.png`);
    },
    getItemThumbnailImage(itemName) {
      return require(`@/assets/images/items/${itemName}.png`);
    },
    onMobileItemThumbnailImageClick: function(refName) {
      console.log(refName);
      console.log(this.$refs.refName);
      this.$refs.refName.$emit("close");
    },
    getItemComponentThumbnailImage(item, componentNumber) {
      const itemWithInformationFromDatabase = this.itemsFromDatabase.filter(
        itemFromDatabase => {
          return itemFromDatabase.key === item;
        }
      );
      return require(`@/assets/images/items/${
        itemWithInformationFromDatabase[0].buildsFrom[componentNumber]
      }.png`);
    },
    getTableEmptyText() {
      if (this.selectedChampions.length === 0) {
        return "No champion entered yet";
      } else if (this.selectedChampions.length === 1) {
        return "Sorry, currently there are no meta compositions that include your given champion";
      } else {
        return "Sorry, currently there are no meta compositions that include your given champions";
      }
    },
    capitalizeFirstLetter: string => {
      return string.charAt(0).toUpperCase() + string.slice(1);
    },
    getSynergiesSorted: function(synergies) {
      return synergies.slice().sort(this.compareSynergyTypes);
    },
    getChampionsSortedByCost: function(champions) {
      return champions.slice().sort(this.compareChampionCost);
    },
    compareChampionCost: function(a, b) {
      if (a.cost < b.cost) {
        return -1;
      }
      if (a.cost > b.cost) {
        return 1;
      }
      return 0;
    },
    compareSynergyTypes: function(a, b) {
      if (a.type < b.type) {
        return -1;
      }
      if (a.type > b.type) {
        return 1;
      }
      return 0;
    },

    convertTierNumberToLetter: function(tierNumber) {
      if (tierNumber === 1) {
        return "S";
      } else if (tierNumber === 2) {
        return "A";
      } else if (tierNumber === 3) {
        return "B";
      } else if (tierNumber >= 4) {
        return "C";
      }
    },

    formatChampionName(championName) {
      if (championName === "AurelionSol") {
        return "Aurelion Sol";
      } else if (championName === "MissFortune") {
        return "Miss Fortune";
      } else if (championName === "Chogath") {
        return "Cho'gath";
      } else if (championName === "RekSai") {
        return "Rek'sai";
      } else if (championName === "Khazix") {
        return "Kha'zix";
      } else {
        return championName;
      }
    }
  },
  created() {
    db.collection("items")
      .get()
      .then(itemsQuerySnapshot => {
        itemsQuerySnapshot.forEach(itemDoc => {
          this.itemsFromDatabase.push(itemDoc.data());
        });
      });
  }
};
</script>

<style lang="scss" scoped>
.popover-body {
  background: #947b4a;
}
.tier-number {
  font-size: 30px;
  font-weight: bold;
  height: 50px;
  width: 52px;
  border: 3px solid #c4ac76;
  border-radius: 50%;
}

.class-or-origin-thumbnail-image {
  height: 45px;
}
.champion-thumbnail {
  -webkit-clip-path: polygon(
    50% 6%,
    89% 24%,
    89% 76%,
    50% 94%,
    11% 74%,
    11% 26%
  );
  clip-path: polygon(50% 6%, 89% 24%, 89% 76%, 50% 94%, 11% 74%, 11% 26%);
}
.champion-thumbnail-image-container {
  display: inline-block;
  position: relative;
  width: 60px;
  height: 60px;
}
.champion-thumbnail-image-container-5-cost {
  background: #f9ce69;
}
.champion-thumbnail-image-container-4-cost {
  background: #601e79;
}
.champion-thumbnail-image-container-3-cost {
  background: #4a9fe0;
}
.champion-thumbnail-image-container-2-cost {
  background: #1e9539;
}
.champion-thumbnail-image-container-1-cost {
  background: #ffffff;
}
.champion-thumbnail-image {
  position: absolute;
  top: 3px;
  left: 3px;
  width: 54px;
  height: 54px;
}
.item-thumbnail-image {
  height: 40px;
  transition: 0.25s;
  transition-timing-function: ease-in-out;

  &:hover {
    transform: scale(1.05);
  }
}

td {
}

td::before {
  text-align: center !important;
  width: 100% !important;
}

td > div {
  padding: 0rem !important;
}

@media screen and (max-width: 768px) {
  .tier-number {
    font-size: 30px;
    font-weight: bold;
    height: 50px;
    width: 52px;
  }
  .class-or-origin-thumbnail-image {
    height: 35px;
  }
  .champion-thumbnail-image-container {
    display: inline-block;
    position: relative;
    width: 50px;
    height: 50px;
  }
  .champion-thumbnail-image {
    position: absolute;
    top: 3px;
    left: 3px;
    width: 44px;
    height: 44px;
  }
  .item-thumbnail-image {
    height: 36px;
  }
  td::before {
    color: #ffffff;
    font-size: 19px;
    margin-bottom: 20px !important;
  }
  td {
    border-bottom: 1px;
    font-weight: bold;
    color: #d3d3d3 !important;
  }
  tr > td:first-of-type > div {
    font-size: 25px !important;
  }
}
</style>
